inherit_from: ./configs/Dynamic/Wild_SLAM_Mocap/crowd_demo_headless.yaml

max_frames: 50

data:
  output: ./output/Wild_SLAM_Mocap_demo_lowvram

cam:
  H_out: 176
  W_out: 320

mono_prior:
  depth: 'metric3d_vit_small'
